### ISSUE TITLE
What should the command for 'next' and so on be called?

### ISSUE THREAD

**Issue by HiPhish** [HiPhish/info.vim#1]
This family of commands is used for navigating to related neighbouring nodes. Here are my suggestions, keep in mind that these commands will only be available in info buffers:

```vim
" append node (currently in use)
:UpNode
:NextNode
:PrevNode

" Prepend info
:InfoUp
:InfoNext
:InfoPrev
```

The variants with `Info` prefix are guaranteed to have at least four suggestions for the first four letters when tab-completing, and unlikely to have more. On the other hand, the suffix versions are unpredictable, they might complete immediately or the user might get a lot of suggestions if other plugins use a similar naming scheme.

Opinions?

**Comment by justinmk** [comment]
Seems complicated. Why can't `InfoNext`, `InfoUp`, `InfoPrev` just do the right thing?

**Comment by HiPhish** [comment]
Oops, I meant `InfoUp` and not `Info`. Edited the OP.

**Comment by HiPhish** [comment]
Last call before I close the issue. Currently there is one vote for `InfoNext`/`InfoUp`/`InfoPrev`, so if no one has to add anything I'll go with that.

**Comment by HiPhish** [comment]
Done, names have been changed to `InfoUp`, `InfoNext` and `InfoPrev`.
