### ISSUE TITLE
<Plug> mappings

### ISSUE THREAD

**Issue by justinmk** [HiPhish/info.vim#2]
I noticed that the `<Plug>Info*` mappings do not use the "parentheses trick". `<Plug>InfoFoo` will trigger a wait for mapping to complete if there is also a `<Plug>InfoFoo2` mapping defined. 

The wait would be avoided if they were defined as `<Plug>(InfoFoo)`  and `<Plug>(InfoFoo2)` . In other words, it's a good practice to always wrap `<Plug>(...)` mappings in parentheses.

Just FYI in case you didn't already know.

**Comment by HiPhish** [comment]
Didn't know that, I'll get to it.

**Comment by HiPhish** [comment]
Done.
