### ISSUE TITLE
propose shell function

### ISSUE THREAD

**Issue by Konfekt** [HiPhish/info.vim#3]
To supplement the built-in info reader, how about proposing in the docs a function, named say `vinfo` in `.bash/zshrc` that calls `:Info`, for example
```
vinfo() {
  vim +"Info "$@"" +only
}
```

**Comment by HiPhish** [comment]
I have let your idea sink in for a few days, and I have concluded not to. Here are my reasons:

- Any information you add to the manual increases its "weight", i.e. it makes it harder to find the one thing you are looking for.
- Shell tricks are neat, but they don't really have anything to do with Vim, so they don't really fit into the manual of a Vim plugin
- There really is nothing tricky about this function call, if you know your shell and you know Vim it's an obvious thing to do. And if you don't know these things it's just magic

None of these reasons are enough on their own, but I think put together they outweigh whatever benefit there might be. I am open to other opinions though, so if you disagree I would like to hear about it.

**Comment by Konfekt** [comment]
Ok, nothing wrong with that. To elaborate: Opposite to your viewpoint that

> Shell tricks are neat, but they don't really have anything to do with Vim.

the proposal was based on people using on my idea that people will use info.vim to replace the info reader by something they are more convenient with, but nowhere it is mentioned how. Just as there is a man reader in Vim, see `:help manpager`. As it was for me the essence of info.vim, I though it merited a shell script one liner.

**Comment by HiPhish** [comment]
I just added the little snippet to the README instead of the manual. I think you are right, it's a handy little trick and the README is short enough that it won't bloat anything.
