### ISSUE TITLE
Deprecated project

### ISSUE THREAD

**Issue by lervag** [HiPhish/info.vim#4]
It seems this repo is "deprecated" in favor of [the one on Gitlab](https://gitlab.com/HiPhish/info.vim). It would be good if you made this clear on the README and/or description.

**Comment by HiPhish** [comment]
It's not supposed to be deprecated, it's supposed to be a mirror for people who prefer GitHub. I'll have to look into the Gitlab settings to see why new commits are not being pushed over to here. Thanks for bringing it up.

**Comment by lervag** [comment]
Ah, sorry. In that case, it seems to be something wrong with the mirror. Happy to help, it seems you're contributing a valuable project, here. Good work!

**Comment by HiPhish** [comment]
OK, the mirror should be set up now properly.

**Comment by lervag** [comment]
Great, thanks!
