### ISSUE TITLE
Using <C-o> to go back to the last jump point freezes Vim

### ISSUE THREAD

**Issue by Ambroisie** [HiPhish/info.vim#6]
When inside an Info documentation, I can move around without any problems and follow link to and from different Info nodes without any problems. However, during normal Vim usage, I usually like to go back to my previous point using <C-o>, which inside an Info document seem to freeze Vim completely.

I don't know if that's a problem coming from my side, or from the plug-in itself (I haven't tested it without any other plug-ins yet, I could try that if needed).

Otherwise thanks for providing this plug-in, I haven't had any other problems using it and it looks great!

**Comment by HiPhish** [comment]
I cannot reproduce this problem. What Info documents are manifesting this behaviour?

**Comment by Ambroisie** [comment]
Well I just tried it again after reinstalling and did not hit the problem this time.

I'm going to close the issue, thanks for your time and for this plug-in.
